### ISSUE TITLE
Check availability of external dependencies

### ISSUE THREAD

**Issue by fredmontet** [timeatlas-dev/timeatlas#36]
As models do use dependencies that are sometimes big, e.g. Prophet or Torch, we don't add them to timeatlas by default. Therefore, if the user wants to make a model using one of those, we need to check its availability before.

**Comment by RychenerLorenz** [comment]
Did you envision something like this:

https://stackoverflow.com/questions/2617704/checking-for-module-availability-programmatically-in-python

**Comment by fredmontet** [comment]
In this issue, one task is also to avoid the import of all models when doing an `import timeatlas as ta`. Otherwise the user has to install all "heavy" dependencies even if he doesn't use them...
