### ISSUE TITLE
Improve TS naming in TSD serialized format

### ISSUE THREAD

**Issue by fredmontet** [timeatlas-dev/timeatlas#6]
At the moment the csv output of TSD has folders that are simply numbered. It's not very nice to ease the understanding of the underlying data. This issue should solve this problem by proposing and implementing a more understandable serialization of each TS in a TSD.

**Comment by RychenerLorenz** [comment]
After discussion and the refactoring of TSD to inherit from List. We leave the naming as 0,1,2,3...,etc.
